import { Property } from "./types";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Villa Moderna en Punta Cana",
    price: "US$850,000",
    address: "Cap Cana, Punta Cana, La Altagracia",
    beds: 4,
    baths: 3,
    sqft: "2,400 m²",
    image: "/villa-punta-cana.png",
    lat: 18.5601,
    lng: -68.3725,
    type: "sale" as const,
  },
  {
    id: "2",
    title: "Apartamento en Bella Vista",
    price: "US$2,800/mes",
    address: "Av. Sarasota, Bella Vista, Santo Domingo",
    beds: 2,
    baths: 2,
    sqft: "120 m²",
    image: "/apartamento-bella-vista.png",
    lat: 18.4655,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "3",
    title: "Casa Colonial en Zona Colonial",
    price: "US$1,200,000",
    address: "Calle Las Damas, Zona Colonial, Santo Domingo",
    beds: 3,
    baths: 2.5,
    sqft: "180 m²",
    image: "/casa-colonial-zona.png",
    lat: 18.4734,
    lng: -69.8834,
    type: "sale" as const,
  },
  {
    id: "4",
    title: "Estudio en Naco",
    price: "US$1,500/mes",
    address: "Calle Fantino Falco, Naco, Santo Domingo",
    beds: 1,
    baths: 1,
    sqft: "60 m²",
    image: "/estudio-naco.png",
    lat: 18.4861,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "5",
    title: "Villa Frente al Mar en Samaná",
    price: "US$950,000",
    address: "Las Terrenas, Samaná",
    beds: 5,
    baths: 4,
    sqft: "280 m²",
    image: "/villa-samana.png",
    lat: 19.3219,
    lng: -69.5392,
    type: "sale" as const,
  },
  {
    id: "6",
    title: "Penthouse en Piantini",
    price: "US$4,500/mes",
    address: "Av. Abraham Lincoln, Piantini, Santo Domingo",
    beds: 3,
    baths: 3,
    sqft: "200 m²",
    image: "/penthouse-piantini.png",
    lat: 18.4734,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "7",
    title: "Casa de Campo en Jarabacoa",
    price: "US$650,000",
    address: "Jarabacoa, La Vega",
    beds: 4,
    baths: 3,
    sqft: "300 m²",
    image: "/mansion-casa-campo.png",
    lat: 19.1167,
    lng: -70.6333,
    type: "sale" as const,
  },
  {
    id: "8",
    title: "Apartamento Vacacional en Cabarete",
    price: "US$150/noche",
    address: "Cabarete, Puerto Plata",
    beds: 2,
    baths: 2,
    sqft: "90 m²",
    image: "/modern-apartment.png",
    lat: 19.75,
    lng: -70.4167,
    type: "vacation" as const,
  },
  {
    id: "9",
    title: "Townhouse en Las Terrenas",
    price: "US$3,200/mes",
    address: "Las Terrenas, Samaná",
    beds: 3,
    baths: 2.5,
    sqft: "160 m²",
    image: "/modern-townhouse.png",
    lat: 19.3219,
    lng: -69.5392,
    type: "rent" as const,
  },
  {
    id: "10",
    title: "Condominio de Lujo en Santo Domingo",
    price: "US$1,800,000",
    address: "Piantini, Santo Domingo",
    beds: 4,
    baths: 4.5,
    sqft: "350 m²",
    image: "/modern-condo.png",
    lat: 18.4734,
    lng: -69.9312,
    type: "sale" as const,
  },
  {
    id: "11",
    title: "Casa Familiar en Santiago",
    price: "US$2,100/mes",
    address: "Santiago de los Caballeros",
    beds: 5,
    baths: 3,
    sqft: "280 m²",
    image: "/modern-single-family-home.png",
    lat: 19.4517,
    lng: -70.697,
    type: "rent" as const,
  },
  {
    id: "12",
    title: "Villa Vacacional en Punta Cana",
    price: "US$400/noche",
    address: "Bávaro, Punta Cana",
    beds: 6,
    baths: 5,
    sqft: "400 m²",
    image: "/luxury-home-with-pool.png",
    lat: 18.5601,
    lng: -68.3725,
    type: "vacation" as const,
  },
  {
    id: "13",
    title: "Apartamento en Zona Colonial",
    price: "US$1,800/mes",
    address: "Zona Colonial, Santo Domingo",
    beds: 2,
    baths: 2,
    sqft: "85 m²",
    image: "/modern-apartment.png",
    lat: 18.4734,
    lng: -69.8834,
    type: "rent" as const,
  },
  {
    id: "14",
    title: "Casa Familiar en Las Terrenas",
    price: "US$1,500,000",
    address: "Las Terrenas, Samaná",
    beds: 4,
    baths: 3.5,
    sqft: "320 m²",
    image: "/modern-single-family-home.png",
    lat: 19.3219,
    lng: -69.5392,
    type: "sale" as const,
  },
  {
    id: "15",
    title: "Penthouse de Lujo en Piantini",
    price: "US$2,500,000",
    address: "Piantini, Santo Domingo",
    beds: 5,
    baths: 4,
    sqft: "450 m²",
    image: "/penthouse-piantini.png",
    lat: 18.4734,
    lng: -69.9312,
    type: "sale" as const,
  },
  {
    id: "16",
    title: "Estudio en Naco",
    price: "US$1,200/mes",
    address: "Naco, Santo Domingo",
    beds: 1,
    baths: 1,
    sqft: "55 m²",
    image: "/estudio-naco.png",
    lat: 18.4861,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "17",
    title: "Villa en Cap Cana",
    price: "US$1,200/noche",
    address: "Cap Cana, Punta Cana",
    beds: 7,
    baths: 6,
    sqft: "500 m²",
    image: "/villa-punta-cana.png",
    lat: 18.5601,
    lng: -68.3725,
    type: "vacation" as const,
  },
  {
    id: "18",
    title: "Townhouse en Santiago",
    price: "US$2,800/mes",
    address: "Santiago de los Caballeros",
    beds: 3,
    baths: 2.5,
    sqft: "180 m²",
    image: "/modern-townhouse.png",
    lat: 19.4517,
    lng: -70.697,
    type: "rent" as const,
  },
];
