export const mockProperties = [
  {
    id: "1",
    title: "Villa Moderna en Punta Cana",
    price: "US$850,000",
    address: "Cap Cana, Punta Cana, La Altagracia",
    beds: 4,
    baths: 3,
    sqft: "2,400 m²",
    image: "/villa-punta-cana.png",
    lat: 18.5601,
    lng: -68.3725,
    type: "sale" as const,
  },
  {
    id: "2",
    title: "Apartamento en Bella Vista",
    price: "US$2,800/mes",
    address: "Av. Sarasota, Bella Vista, Santo Domingo",
    beds: 2,
    baths: 2,
    sqft: "120 m²",
    image: "/apartamento-bella-vista.png",
    lat: 18.4655,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "3",
    title: "Casa Colonial en Zona Colonial",
    price: "US$1,200,000",
    address: "Calle Las Damas, Zona Colonial, Santo Domingo",
    beds: 3,
    baths: 2.5,
    sqft: "180 m²",
    image: "/casa-colonial-zona.png",
    lat: 18.4734,
    lng: -69.8834,
    type: "sale" as const,
  },
  {
    id: "4",
    title: "Estudio en Naco",
    price: "US$1,500/mes",
    address: "Calle Fantino Falco, Naco, Santo Domingo",
    beds: 1,
    baths: 1,
    sqft: "60 m²",
    image: "/estudio-naco.png",
    lat: 18.4861,
    lng: -69.9312,
    type: "rent" as const,
  },
  {
    id: "5",
    title: "Villa Frente al Mar en Samaná",
    price: "US$950,000",
    address: "Las Terrenas, Samaná",
    beds: 5,
    baths: 4,
    sqft: "280 m²",
    image: "/villa-samana.png",
    lat: 19.3219,
    lng: -69.5392,
    type: "sale" as const,
  },
  {
    id: "6",
    title: "Penthouse en Piantini",
    price: "US$4,500/mes",
    address: "Av. Abraham Lincoln, Piantini, Santo Domingo",
    beds: 3,
    baths: 3,
    sqft: "200 m²",
    image: "/penthouse-piantini.png",
    lat: 18.4734,
    lng: -69.9312,
    type: "rent" as const,
  },
]
